### ISSUE TITLE
The class names are wrong for 1.11.2

### ISSUE THREAD

**Issue by Cutiemango** [digitalshadowhawk/Omniscience#1]
1.11.2:
net.minecraft.entity.Entity = aay.class

net.minecraft.entity.player.EntityPlayer = sn.class

net.minecraft.client.renderer.RenderGlobal = bqm.class

**Comment by digitalshadowhawk** [comment]
I don't control the specific obfuscation applied to specific classes. That's all up to ForgeGradle, and the mappings it was compiled against at the time worked.

**Comment by Cutiemango** [comment]
Have you tried the mod in 1.11.2? It doesn't work for LiteLoader 1.11.2.
After correcting these class names above, I tested it and it worked.

**Comment by digitalshadowhawk** [comment]
How new is your installation of LiteLoader 1.11.2? It could be that the version of Omniscience I have works with the release of LiteLoader I have installed, but that Mumfrey's updated it since with new, incompatible mappings. I run it on my instance of minecraft on a 1.11.2 server to help me manage players, and it works fine for me, so this is the only explanation I can come up with.
